config/routes.rb
Rails.application.routes.draw do
  root to: 'schedules#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'todaiphil', to: 'users#new'
  get 'uraindex', to: 'sessions#uraindex'
  
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :schedules do
    member do
      get :section
      get :whole
      get :piece_1
      get :piece_2
      get :piece_3
    end
  end
  resources :answers, only: [:new, :create, :destroy, :update, :edit]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true, length: { maximum: 255 }
  validates :event, presence: true, length: {maximum: 50 }
  validates :event_date, presence: true
  validate :date_cannot_be_in_the_past
  validates :location, length: {maximum: 255}
  validates :detail, length: {maximum: 255}
  
  has_many :answers, dependent: :destroy
  
  def date_cannot_be_in_the_past
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, ": 過去の日付は使用できません")
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  require 'date'
  
  def index
    @schedules = Schedule.where("event_date >= ?", Date.current).order(:event_date).page(params[:page]).per(50)
    @answers = Answer.all
    past_schedules = Schedule.where("event_date < ?", Date.current)
    past_schedules.each do |past_schedule|
        past_schedule.destroy
    end
    @weeks = ["月", "火", "水", "木", "金", "土", "日"]
  end
  
  def show
    @schedule = Schedule.find(params[:id])
    @users = User.where(part: current_user.part).page(params[:page]).per(70)
    @count_users = User.where(part: current_user.part)
    counts(@schedule, @count_users)
    @weeks = ["月", "火", "水", "木", "金", "土", "日"]
  end

  def new
    @schedule = current_user.schedules.build
    @schedule.location = "音楽実習室"
    @schedule.start_at = "2000-01-01 14:00:00"
    @schedule.end_at = "2000-01-01 17:00:00"
    @schedule.event = "合奏"
  end
  
  def create
    @schedule = current_user.schedules.build(schedule_params)
    @schedule.update(user_id: current_user.id)
    if @schedule.save
      flash[:success] = '予定を作成しました！'
      redirect_to @schedule
    else
      flash.now[:danger] = '予定を作成できませんでした...'
      render :new
    end
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash[:success] = '予定は正常に更新されました！'
      redirect_to @schedule
    else
      flash.now[:danger] = '予定は更新されませんでした...'
      render :edit
    end
  end
  
  def destroy
    @schedule.destroy
    flash[:success] = '予定を削除してしまいました！'
    redirect_to root_url
  end
  
  def section
    s = current_user.section
    @schedule = Schedule.find(params[:id])
    if s == 3 || s == 4
      @users = User.where(["section=? or section=?", '3', '4']).order(:instrument).page(params[:page]).per(100)
      @count_users = User.where(["section=? or section=?", '3', '4'])
    else
      @users = User.where(["section=? or section=?", '1',  '2']).order(:instrument).page(params[:page]).per(100)
      @count_users = User.where(["section=? or section=?", '1',  '2'])
    end
    counts(@schedule, @count_users)
    @weeks = ["月", "火", "水", "木", "金", "土", "日"]
  end
  
  def whole
    @schedule = Schedule.find(params[:id])
    @users = User.all.order(:instrument).page(params[:page]).per(500)
    @count_users = User.all
    counts(@schedule, @count_users)
    @weeks = ["月", "火", "水", "木", "金", "土", "日"]
  end
  
  def piece_1
    @schedule = Schedule.find(params[:id])
    @users = User.where(["piece_1=? or piece_1=? or piece_1=?", '本乗り', 'アシ', 'トラ']).order(:instrument).page(params[:page]).per(500)
    @count_users = User.all
    counts(@schedule, @count_users)
  end
  
  def piece_2
    @schedule = Schedule.find(params[:id])
    @users = User.where(["piece_2=? or piece_2=? or piece_2=?", '本乗り', 'アシ', 'トラ']).order(:instrument).page(params[:page]).per(500)
    @count_users = User.all
    counts(@schedule, @count_users)
  end
  
  def piece_3
    @schedule = Schedule.find(params[:id])
    @users = User.where(["piece_3=? or piece_3=? or piece_3=?", '本乗り', 'アシ', 'トラ']).order(:instrument).page(params[:page]).per(500)
    @count_users = User.all
    counts(@schedule, @count_users)
  end
  
  private
  
  def schedule_params
    params.require(:schedule).permit(:event, :event_date, :start_at, :end_at, :location, :detail)
  end
  
  def correct_user
    @schedule = current_user.schedules.find_by(id: params[:id])
    unless @schedule
      redirect_to root_url
    end
  end
end

app/views/schedules/_modal.html.erb
<% if current_user.reaction?(schedule) %>
  <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#schedule<%= schedule.id%>">編集</button>
  <div class="modal fade" id="schedule<%= schedule.id%>" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <%= schedule.location %>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modal-label<%= schedule.id%>"><%= schedule.event %></h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%= form_for(current_user.answers.find_by(schedule_id: schedule.id), html: {method: :put}) do |f| %>
                <%= hidden_field_tag :schedule_id, schedule.id %>
                <div class="btn-group" data-toggle="buttons">
                  <label class="btn btn-success"><i class="glyphicon glyphicon-ok-sign"></i><%= f.radio_button :status, '◯' %><br>参加</label>
                  <label class="btn btn-warning"><i class="glyphicon glyphicon-exclamation-sign"></i><%= f.radio_button :status, '△' %><br>遅/早</label>
                  <label class="btn btn-danger"><i class="glyphicon glyphicon-remove-sign"></i><%= f.radio_button :status, '×' %><br>欠席</label>
                  <label class="btn btn-default"><i class="glyphicon glyphicon-question-sign"></i><%= f.radio_button :status, '？' %><br>保留</label>
                </div>
                <div class="form-group">
                  <br>
                  <%= f.label :comment, 'コメント（欠席/遅刻早退の理由）' %>
                  <%= f.text_field :comment, class: 'form-control' %>
                </div>
                <%= f.submit '編集完了', class: 'btn btn-success btn-ms center-block' %>
              <% end %>
              <%= form_for(current_user.answers.find_by(schedule_id: schedule.id), html: {method: :delete}) do |f| %>
                <%= hidden_field_tag :schedule_id, schedule.id %>
                <%= f.submit 'リセット', class: 'btn btn-default btn-xs' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#schedule<%= schedule.id %>">回答</button>
  <div class="modal fade" id="schedule<%= schedule.id%>" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <%= schedule.location %>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modal-label<%= schedule.id %>"><%= schedule.event %></h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%= form_for(current_user.answers.build) do |f| %>
                <%= hidden_field_tag :schedule_id, schedule.id %>
                <div class="btn-group" data-toggle="buttons">
                  <label class="btn btn-success"><i class="glyphicon glyphicon-ok-sign"></i><%= f.radio_button :status, '◯' %><br>参加</label>
                  <label class="btn btn-warning"><i class="glyphicon glyphicon-exclamation-sign"></i><%= f.radio_button :status, '△' %><br>遅/早</label>
                  <label class="btn btn-danger"><i class="glyphicon glyphicon-remove-sign"></i><%= f.radio_button :status, '×' %><br>欠席</label>
                  <label class="btn btn-default"><i class="glyphicon glyphicon-question-sign"></i><%= f.radio_button :status, '？' %><br>保留</label>
                </div>
                <div class="form-group">
                  <br>
                  <%= f.label :comment, 'コメント(欠席/遅刻早退の理由)' %>
                  <%= f.text_field :comment, class: 'form-control' %>
                </div>
                <%= f.submit '回答', class: 'btn btn-primary btn-ms center-block' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/schedules/_piece1.html.erb
<div class="col-xs-12">
  <table class="table table-striped">
    
    <thread>
      <tr>
        <th>パート</th>
        <th>名前</th>
        <th>回答</th>
        <th>ステータス</th>
      </tr>
    </thread>
    
    <tbody>
        <% users.each do |user| %>
          <% if user.alive? %>
            <tr>
              <td><%= user.part %></td>
              <td><%= user.name %></td>
                <% if user.reaction?(schedule) %>
                  <% his_answer = user.answers.find_by(schedule_id: schedule.id) %>
                  <td><%= his_answer.status %></td>
                  <td><%= user.piece_1 %></td>
                <% else %>
                  <td>ー</td>
                  <td><%= user.piece_1 %></td>
                <% end %>
            </tr>
          <% else %>
            <tr></tr>
          <% end %>
        <% end %>
    </tbody>
    
     <%= paginate users %>
     
  </table>
</div>

app/views/schedules/_piece2.html.erb
<div class="col-xs-12">
  <table class="table table-striped">
    
    <thread>
      <tr>
        <th>パート</th>
        <th>名前</th>
        <th>回答</th>
        <th>ステータス</th>
      </tr>
    </thread>
    
    <tbody>
        <% users.each do |user| %>
          <% if user.alive? %>
            <tr>
              <td><%= user.part %></td>
              <td><%= user.name %></td>
                <% if user.reaction?(schedule) %>
                  <% his_answer = user.answers.find_by(schedule_id: schedule.id) %>
                  <td><%= his_answer.status %></td>
                  <td><%= user.piece_2 %></td>
                <% else %>
                  <td>ー</td>
                  <td><%= user.piece_2 %></td>
                <% end %>
            </tr>
          <% else %>
            <tr></tr>
          <% end %>
        <% end %>
    </tbody>
    
     <%= paginate users %>
     
  </table>
</div>

app/views/schedules/_piece3.html.erb
<div class="col-xs-12">
  <table class="table table-striped">
    
    <thread>
      <tr>
        <th>パート</th>
        <th>名前</th>
        <th>回答</th>
        <th>ステータス</th>
      </tr>
    </thread>
    
    <tbody>
        <% users.each do |user| %>
          <% if user.alive? %>
            <tr>
              <td><%= user.part %></td>
              <td><%= user.name %></td>
                <% if user.reaction?(schedule) %>
                  <% his_answer = user.answers.find_by(schedule_id: schedule.id) %>
                  <td><%= his_answer.status %></td>
                  <td><%= user.piece_3 %></td>
                <% else %>
                  <td>ー</td>
                  <td><%= user.piece_3 %></td>
                <% end %>
            </tr>
          <% else %>
            <tr></tr>
          <% end %>
        <% end %>
    </tbody>
    
     <%= paginate users %>
     
  </table>
</div>

app/views/schedules/edit.html.erb
<div class="text-center">
  <h1>日程の編集</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@schedule) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <% hidden_field_tag :user_id, current_user.id %>
      <div class="form-group">
        <%= f.label :event, 'イベント名' %>
        <%= f.text_field :event, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :event_date, '日付' %>
        <%= f.date_field :event_date, {} %>
      </div>
      <div class="form-group time">
        <%= f.label :start_at, '開始' %><br>
        <%= f.time_field :start_at, {} %>
      </div>
      <div class="mtime"><br>〜</div>
      <div class="form-group time">
        <%= f.label :end_at, '終了' %><br>
        <%= f.time_field :end_at, {} %>
      </div>
      <div class="form-group location">
        <%= f.label :location, '場所' %>
        <%= f.text_field :location, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :detail, '詳細' %>
        <%= f.text_area :detail, class: 'form-control' %>
      </div>
      <%= f.submit '完了', class: 'btn btn-primary btn-ms center-block' %>
    <% end %>
  </div>
</div>

app/views/schedules/index.html.erb
<% if logged_in? %>
  <% time_japan = Time.now.getlocal("+09:00") %>
  <% if 5 <= time_japan.hour && time_japan.hour < 11 %>
    <p>おはようございます、<%= current_user.name %>さん</p>
  <% elsif 11 <= time_japan.hour && time_japan.hour < 17 %>
    <p>こんにちは、<%= current_user.name %>さん</p>
  <% else %>
    <p>こんばんは、<%= current_user.name %>さん</p>
  <% end %>
<div class="row">
  <div class="col-xs-12">
    <table class="table table-striped">
      <thread>
        <tr>
          <th>日時</th>
          <th>内容</th>
          <th>場所</th>
          <th>回答</th>
          <th> </th>
        </tr>
      </thread>
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr id=<%= schedule.id%>>
            <td class="date" name=<% date=schedule.event_date %><%= date.strftime('%Y%m%d') %>><%= date.strftime('%-m/%-d (') %><% week = date.strftime('%u').to_i - 1 %><%= @weeks[week] %><%= ')' %><br><% stime = schedule.start_at %><%= stime.strftime('%H:%M') %>〜<% etime = schedule.end_at %><%= etime.strftime('%H:%M') %></td>
            <% if current_user.reaction?(schedule) %>
              <td class="event"><%= link_to  schedule.event, schedule %></td>
            <% else %>
              <td class="event"><%= schedule.event %></td>
            <% end %>
              <td class="location"><%= schedule.location %></td>
            <% if current_user.reaction?(schedule) %>
              <td class="answer"><%= @answers.find_by(schedule_id: schedule.id, user_id: current_user.id).status %></td>
            <% else %>
              <td class="answer">ー</td>
            <% end %>
            <td><%= render 'schedules/modal', schedule: schedule %></td>
          </tr>
        <% end %>
      </tbody>
       <%= paginate @schedules %>
    </table>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>シンプルで使いやすい出欠管理を始めましょう</h1>
    <%= link_to '会員登録', todaiphil_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>
<% end %>

app/views/schedules/new.html.erb
<div class="text-center">
  <h1>新規作成</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@schedule) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :event, 'イベント名' %>
        <%= f.text_field :event, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :event_date, '日付' %>
        <%= f.date_field( :event_date) %>
      </div>
      <div class="form-group time">
        <%= f.label :start_at, '開始' %><br>
        <%= f.time_field(:start_at, :step => 300) %>
      </div>
      <div class="mtime"><br>〜</div>
      <div class="form-group time">
        <%= f.label :end_at, '終了' %><br>
        <%= f.time_field(:end_at, :step => 300) %>
      </div>
      <div class="form-group location">
        <%= f.label :location, '場所' %>
        <%= f.text_field :location , class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :detail, '詳細' %>
        <%= f.text_area :detail, class: 'form-control' %>
      </div>
      <%= f.submit '作成', class: 'btn btn-primary btn-ms center-block' %>
    <% end %>
  </div>
</div>

app/views/schedules/piece_1.html.erb
<div>
  <h3><%= @schedule.event %></h3>
  <h4>場所：<%= @schedule.location%></h4>
  <p><% date=@schedule.event_date %><%= date.strftime('%m月%d日 (%a)') %><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre><p><%= @schedule.detail %></p></pre>
  <p>作成者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>

<div>
  <p>出席者:<%= @attend_counts %></p>
  <p>遅刻者:<%= @late_counts %></p>
  <p>欠席者:<%= @absent_counts %></p>
</div>
<br>
<%= link_to '通常表示へ', schedule_path(@schedule) %>

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(piece_1_schedule_path(@schedule)) %>"><%= link_to piece_1_schedule_path(@schedule) do %>前プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_2_schedule_path(@schedule)) %>"><%= link_to piece_2_schedule_path(@schedule) do %>中プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_3_schedule_path(@schedule)) %>"><%= link_to piece_3_schedule_path(@schedule) do %>メイン<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'piece1', users: @users, schedule: @schedule %>
</div>

app/views/schedules/piece_2.html.erb
<div>
  <h3><%= @schedule.event %></h3>
  <h4>場所：<%= @schedule.location%></h4>
  <p><% date=@schedule.event_date %><%= date.strftime('%m月%d日 (%a)') %><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre><p><%= @schedule.detail %></p></pre>
  <p>作成者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>

<div>
  <p>出席者:<%= @attend_counts %></p>
  <p>遅刻者:<%= @late_counts %></p>
  <p>欠席者:<%= @absent_counts %></p>
</div>
<br>
<%= link_to '通常表示へ', schedule_path(@schedule) %>

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(piece_1_schedule_path(@schedule)) %>"><%= link_to piece_1_schedule_path(@schedule) do %>前プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_2_schedule_path(@schedule)) %>"><%= link_to piece_2_schedule_path(@schedule) do %>中プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_3_schedule_path(@schedule)) %>"><%= link_to piece_3_schedule_path(@schedule) do %>メイン<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'piece2', users: @users, schedule: @schedule %>
</div>

app/views/schedules/piece_3.html.erb
<div>
  <h3><%= @schedule.event %></h3>
  <h4>場所：<%= @schedule.location%></h4>
  <p><% date=@schedule.event_date %><%= date.strftime('%m月%d日 (%a)') %><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre><p><%= @schedule.detail %></p></pre>
  <p>作成者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>

<div>
  <p>出席者:<%= @attend_counts %></p>
  <p>遅刻者:<%= @late_counts %></p>
  <p>欠席者:<%= @absent_counts %></p>
</div>

<br>
<%= link_to '通常表示へ', schedule_path(@schedule) %>

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(piece_1_schedule_path(@schedule)) %>"><%= link_to piece_1_schedule_path(@schedule) do %>前プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_2_schedule_path(@schedule)) %>"><%= link_to piece_2_schedule_path(@schedule) do %>中プロ<% end %></li>
    <li class="<%= 'active' if current_page?(piece_3_schedule_path(@schedule)) %>"><%= link_to piece_3_schedule_path(@schedule) do %>メイン<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'piece3', users: @users, schedule: @schedule %>
</div>

app/views/schedules/section.html.erb
<div>
  <h3><%= @schedule.event %></h3>
  <h4>場所：<%= @schedule.location%></h4>
  <p><% date=@schedule.event_date %><%= date.strftime('%-m月%-d日(') %><%= @weeks[ date.strftime('%u').to_i - 1]%><%= ')'%><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre><p><%= @schedule.detail %></p></pre>
  <p>作成者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>

<div>
  <p>出席:<%= @attend_counts %></p>
  <p>遅刻:<%= @late_counts %></p>
  <p>欠席:<%= @absent_counts %></p>
</div>
<br>
<%= link_to '乗り番参照モードへ', piece_1_schedule_path(@schedule) %>

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(schedule_path(@schedule)) %>"><%= link_to schedule_path(@schedule) do %>パート<% end %></li>
    <li class="<%= 'active' if current_page?(section_schedule_path(@schedule)) %>"><%= link_to section_schedule_path(@schedule) do %>セクション<% end %></li>
    <li class="<%= 'active' if current_page?(whole_schedule_path(@schedule)) %>"><%= link_to whole_schedule_path(@schedule) do %>全体<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'reactions', users: @users, schedule: @schedule %>
</div>

app/views/schedules/show.html.erb
<div>
  <h3 class="event"><%= @schedule.event %></h3>
  <h4 class="location" name=<%= @schedule.location%>>場所：<%= @schedule.location%></h4>
  <p class="date" name=<% date=@schedule.event_date %><%= date.strftime('%m%d') %>><%= date.strftime('%-m月%-d日(') %><%= @weeks[ date.strftime('%u').to_i - 1]%><%= ')'%><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre class="detail"><p><%= @schedule.detail %></p></pre>
  <p>最終編集者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user || current_user.admin == true %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>
<div>
  <p>出席:<%= @attend_counts %></p>
  <p>遅刻:<%= @late_counts %></p>
  <p>欠席:<%= @absent_counts %></p>
</div>

<br>
<%= link_to '乗り番参照モードへ', piece_1_schedule_path(@schedule) %>


  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(schedule_path(@schedule)) %>"><%= link_to schedule_path(@schedule) do %>パート<% end %></li>
    <li class="<%= 'active' if current_page?(section_schedule_path(@schedule)) %>"><%= link_to section_schedule_path(@schedule) do %>セクション<% end %></li>
    <li class="<%= 'active' if current_page?(whole_schedule_path(@schedule)) %>"><%= link_to whole_schedule_path(@schedule) do %>全体<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'reactions', users: @users, schedule: @schedule %>
</div>

app/views/schedules/whole.html.erb
<div>
  <h3><%= @schedule.event %></h3>
  <h4>場所：<%= @schedule.location%></h4>
  <p><% date=@schedule.event_date %><%= date.strftime('%-m月%-d日(') %><%= @weeks[ date.strftime('%u').to_i - 1]%><%= ')'%><% stime = @schedule.start_at %>   <%= stime.strftime('%H:%M') %>〜<% etime = @schedule.end_at %><%= etime.strftime('%H:%M') %></p>
  <pre><p><%= @schedule.detail %></p></pre>
  <p>最終編集者：<%= @schedule.user.name %></p>
</div>

<div>
  <%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary' %>
  <%= link_to '編集する', edit_schedule_path(@schedule), class: 'btn btn-success' %>
  <% if current_user == @schedule.user %>
    <%= link_to '削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  <% end %>
</div>

<br>

<div>
  <p>出席:<%= @attend_counts %></p>
  <p>遅刻:<%= @late_counts %></p>
  <p>欠席:<%= @absent_counts %></p>
</div>
<br>
<%= link_to '乗り番参照モードへ', piece_1_schedule_path(@schedule) %>

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(schedule_path(@schedule)) %>"><%= link_to schedule_path(@schedule) do %>パート<% end %></li>
    <li class="<%= 'active' if current_page?(section_schedule_path(@schedule)) %>"><%= link_to section_schedule_path(@schedule) do %>セクション<% end %></li>
    <li class="<%= 'active' if current_page?(whole_schedule_path(@schedule)) %>"><%= link_to whole_schedule_path(@schedule) do %>全体<% end %></li>
  </ul>
<div class="col-xs-12">
  <%= render 'reactions', users: @users, schedule: @schedule %>
</div>